# Generated by Django 4.2.27 on 2025-12-10 15:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('roles_assigned', 'roles_assigned'), ('guess_submitted', 'guess_submitted'), ('result', 'result')], default='waiting', max_length=32)),
                ('roles', models.JSONField(blank=True, null=True)),
                ('mantri_guess', models.JSONField(blank=True, null=True)),
                ('round_result', models.JSONField(blank=True, null=True)),
                ('round', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
            options={
                'unique_together': {('room', 'player')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(through='game.RoomPlayer', to='game.player'),
        ),
    ]
